services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8040:8080"
    command:
      - start-dev
    restart: always
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
    driver: local
