server:
  port: 8087

spring:
  application:
    name: inventory-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8040/realms/demo-app
          jwk-set-uri: http://localhost:8040/realms/demo-app/protocol/openid-connect/certs
eureka:
  client:
    enabled: false
